# -*- coding: utf-8 -*-
"""(PA)Q4By praise Yakubu 20006951

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nk1L6gvOO3SBuViFDCNmt3j5ibpVuCYF
"""

phone_book = {}
#prompt the user to add a phone number
def add_contact():
    name = input("Enter the contact's name: ")
    number = input("Enter the contact's phone number: ")

    if number not in phone_book.values():
        phone_book[name] = number
        print(f"Contact {name} with phone number {number} added successfully.")
    else:
        print("Phone number already exists. Contact not added.")
#user delete an already existing contact.
def delete_contact():
    name = input("Enter the contact's name to delete: ")

    if name in phone_book:
        del phone_book[name]
        print(f"Contact {name} deleted successfully.")
    else:
        print(f"Contact {name} not found.")
#prompt the user to add a number to an already existing
def update_contact(): #user updates  an already existing Contacts name and number
    name = input("Update the contact's name:")
    number = input("Add another number to the contact's phone number:")

    if number in phone_book.values():
        phone_book[name] = number
        print(f"Contact {name} with phone number {number} added successfully.")
    else:
        print("Phone number already exists. Contact not added.")
#user searches the phone book for an already exsiting phone conatct
def lookup_contact():
    name = input("Enter the contact's name to lookup: ")

    if name in phone_book:
        print(f"Contact {name}: {phone_book[name]}")
    else:
        print(f"Contact {name} not found.")
#prompt the user to enter a number for a function to run
while True:
    print("\nPhone Book Menu:")
    print("1. Add Contact")
    print("2. Delete Contact")
    print("3. update_contact")
    print("4. Lookup Contact")
    print("5. Quit")

    choice = input("Enter your choice (1-5): ")

    if choice == '1':
        add_contact()
    elif choice == '2':
        delete_contact()
    elif choice == '3':
     update_contact()
    elif choice == '4':
        lookup_contact()
    elif choice == '5':
        print("Exiting the phone book. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number between 1 and 5.")